# Generated by Django 3.0.6 on 2020-06-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aureum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.CharField(blank=True, max_length=445, null=True)),
                ('header', models.CharField(blank=True, max_length=445, null=True)),
                ('eng_name', models.CharField(blank=True, max_length=445, null=True)),
                ('acc_name', models.CharField(blank=True, max_length=445, null=True)),
                ('value', models.CharField(blank=True, max_length=445, null=True)),
                ('unit', models.CharField(blank=True, max_length=445, null=True)),
                ('year', models.DateTimeField(blank=True, null=True)),
                ('statement', models.CharField(blank=True, max_length=445, null=True)),
                ('report_period', models.DateTimeField(blank=True, null=True)),
                ('filing_type', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'balance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.CharField(blank=True, max_length=445, null=True)),
                ('header', models.CharField(blank=True, max_length=445, null=True)),
                ('eng_name', models.CharField(blank=True, max_length=445, null=True)),
                ('acc_name', models.CharField(blank=True, max_length=445, null=True)),
                ('value', models.CharField(blank=True, max_length=445, null=True)),
                ('unit', models.CharField(blank=True, max_length=445, null=True)),
                ('year', models.DateTimeField(blank=True, null=True)),
                ('statement', models.CharField(blank=True, max_length=445, null=True)),
                ('report_period', models.DateTimeField(blank=True, null=True)),
                ('filing_type', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'income',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='BalanceSheet',
        ),
        migrations.DeleteModel(
            name='Context',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='IncomeStatement',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
